//
// KudosTransferBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct KudosTransferBody: Codable {
    public var username: String?
    public var amount: Int?

    public init(username: String? = nil, amount: Int? = nil) {
        self.username = username
        self.amount = amount
    }
}
