//
// TeamsGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TeamsGetResponse: Codable {
    /** The unique identifier for this team */
    public var _id: String?
    /** The name of this team */
    public var teamName: String?
    /** Whether this team is private or not */
    public var isPrivate: Bool?

    public init(_id: String? = nil, teamName: String? = nil, isPrivate: Bool? = nil) {
        self._id = _id
        self.teamName = teamName
        self.isPrivate = isPrivate
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case teamName = "team_name"
        case isPrivate = "is_private"
    }
}
