//
// CreateTeamInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTeamInput: Codable {

    /** The name of the team. No profanity allowed! */
    public var name: String
    /** Extra information or comments about this team. */
    public var info: String?

    public init(name: String, info: String? = nil) {
        self.name = name
        self.info = info
    }


}
