//
// KudosTransferred.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct KudosTransferred: Codable {

    /** The amount of Kudos tranferred */
    public var transferred: Int?

    public init(transferred: Int? = nil) {
        self.transferred = transferred
    }


}
