//
// WorkerDetailsLite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkerDetailsLite: Codable {

    public enum ModelType: String, Codable { 
        case image = "image"
        case text = "text"
        case interrogation = "interrogation"
    }
    /** The Type of worker this is. */
    public var type: ModelType?
    /** The Name given to this worker. */
    public var name: String?
    /** The UUID of this worker. */
    public var _id: String?
    /** True if the worker has checked-in the past 5 minutes. */
    public var online: Bool?

    public init(type: ModelType? = nil, name: String? = nil, _id: String? = nil, online: Bool? = nil) {
        self.type = type
        self.name = name
        self._id = _id
        self.online = online
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case name
        case _id = "id"
        case online
    }

}
