//
// ActiveModelLite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActiveModelLite: Codable {

    /** The Name of a model available by workers in this horde. */
    public var name: String?
    /** How many of workers in this horde are running this model. */
    public var count: Int?

    public init(name: String? = nil, count: Int? = nil) {
        self.name = name
        self.count = count
    }


}
