//
// DeleteTimeoutIPInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct DeleteTimeoutIPInput: Codable {
    /** The IP address to remove from timeout */
    public var ipaddr: String

    public init(ipaddr: String) {
        self.ipaddr = ipaddr
    }
}
