//
// FilterRegex.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct FilterRegex: Codable {
    /** The integer defining this filter type */
    public var filterType: Int
    /** The full regex for this filter type. */
    public var regex: String

    public init(filterType: Int, regex: String) {
        self.filterType = filterType
        self.regex = regex
    }

    public enum CodingKeys: String, CodingKey {
        case filterType = "filter_type"
        case regex
    }
}
