//
// FilterDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FilterDetails: Codable {

    /** The UUID of this filter. */
    public var _id: String
    /** The regex for this filter. */
    public var regex: String
    /** The integer defining this filter type */
    public var filterType: Int
    /** Description about this regex */
    public var _description: String?
    /** The replacement string for this regex. */
    public var replacement: String?
    /** The moderator which added or last updated this regex */
    public var user: String

    public init(_id: String, regex: String, filterType: Int, _description: String? = nil, replacement: String? = nil, user: String) {
        self._id = _id
        self.regex = regex
        self.filterType = filterType
        self._description = _description
        self.replacement = replacement
        self.user = user
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case regex
        case filterType = "filter_type"
        case _description = "description"
        case replacement
        case user
    }

}
