//
// GenerationSubmitted.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GenerationSubmitted: Codable {
    /** The amount of kudos gained for submitting this request */
    public var reward: Decimal?

    public init(reward: Decimal? = nil) {
        self.reward = reward
    }
}
