//
// Generation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Generation: Codable {
    public enum State: String, Codable {
        case ok
        case censored
    }

    /** The UUID of the worker which generated this image */
    public var workerId: String?
    /** The name of the worker which generated this image */
    public var workerName: String?
    /** The model which generated this image */
    public var model: String?
    /** The state of this generation. */
    public var state: State

    public init(workerId: String? = nil, workerName: String? = nil, model: String? = nil, state: State) {
        self.workerId = workerId
        self.workerName = workerName
        self.model = model
        self.state = state
    }

    public enum CodingKeys: String, CodingKey {
        case workerId = "worker_id"
        case workerName = "worker_name"
        case model
        case state
    }
}
