//
// GenerationKobold.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GenerationKobold: Codable {
    public enum State: String, Codable {
        case ok
        case censored
    }

    /** The UUID of the worker which generated this image */
    public var workerId: String?
    /** The name of the worker which generated this image */
    public var workerName: String?
    /** The model which generated this image */
    public var model: String?
    /** The state of this generation. */
    public var state: State
    /** The generated text. */
    public var text: String?
    /** The seed which generated this text */
    public var seed: Int?

    public init(workerId: String? = nil, workerName: String? = nil, model: String? = nil, state: State, text: String? = nil, seed: Int? = nil) {
        self.workerId = workerId
        self.workerName = workerName
        self.model = model
        self.state = state
        self.text = text
        self.seed = seed
    }

    public enum CodingKeys: String, CodingKey {
        case workerId = "worker_id"
        case workerName = "worker_name"
        case model
        case state
        case text
        case seed
    }
}
