//
// HordeModes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct HordeModes: Codable {
    /** When True, this Horde will not accept new requests for image generation, but will finish processing the ones currently in the queue. */
    public var maintenanceMode: Bool?
    /** When True, this Horde will not only accept worker explicitly invited to join. */
    public var inviteOnlyMode: Bool?
    /** When True, this Horde will not always provide full information in order to throw off attackers. */
    public var raidMode: Bool?

    public init(maintenanceMode: Bool? = nil, inviteOnlyMode: Bool? = nil, raidMode: Bool? = nil) {
        self.maintenanceMode = maintenanceMode
        self.inviteOnlyMode = inviteOnlyMode
        self.raidMode = raidMode
    }

    public enum CodingKeys: String, CodingKey {
        case maintenanceMode = "maintenance_mode"
        case inviteOnlyMode = "invite_only_mode"
        case raidMode = "raid_mode"
    }
}
