//
// InterrogationStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InterrogationStatus: Codable {

    /** The overall status of this interrogation */
    public var state: String?
    public var forms: [InterrogationFormStatus]?

    public init(state: String? = nil, forms: [InterrogationFormStatus]? = nil) {
        self.state = state
        self.forms = forms
    }


}
