//
// InterrogationFormStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InterrogationFormStatus: Codable {

    /** The name of this interrogation form */
    public var form: String?
    /** The overall status of this interrogation */
    public var state: String?
    public var result: String?

    public init(form: String? = nil, state: String? = nil, result: String? = nil) {
        self.form = form
        self.state = state
        self.result = result
    }


}
