//
// KaiUserIdBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct KaiUserIdBody: Codable {

    public var kaiId: Int?
    public var kudosAmount: Int?
    public var trusted: Bool?

    public init(kaiId: Int? = nil, kudosAmount: Int? = nil, trusted: Bool? = nil) {
        self.kaiId = kaiId
        self.kudosAmount = kudosAmount
        self.trusted = trusted
    }

    public enum CodingKeys: String, CodingKey { 
        case kaiId = "kai_id"
        case kudosAmount = "kudos_amount"
        case trusted
    }

}
