//
// KudosAwarded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct KudosAwarded: Codable {
    /** The amount of Kudos awarded */
    public var awarded: Int?

    public init(awarded: Int? = nil) {
        self.awarded = awarded
    }
}
