//
// ModelInterrogationInputStable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ModelInterrogationInputStable: Codable {
    public var forms: [ModelInterrogationFormStable]?
    /** The public URL of the image to interrogate */
    public var sourceImage: String?
    /** When True, allows slower workers to pick up this request. Disabling this incurs an extra kudos cost. */
    public var slowWorkers: Bool?

    public init(forms: [ModelInterrogationFormStable]? = nil, sourceImage: String? = nil, slowWorkers: Bool? = nil) {
        self.forms = forms
        self.sourceImage = sourceImage
        self.slowWorkers = slowWorkers
    }

    public enum CodingKeys: String, CodingKey {
        case forms
        case sourceImage = "source_image"
        case slowWorkers = "slow_workers"
    }
}
