//
// ModelPayloadLorasStable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ModelPayloadLorasStable: Codable {
    /** The exact name of the LoRa */
    public var name: String
    /** The strength of the LoRa to apply to the SD model. */
    public var model: Decimal?
    /** The strength of the LoRa to apply to the clip model. */
    public var clip: Decimal?
    /** If set, will try to discover a trigger for this LoRa which matches or is similar to this string and inject it into the prompt. I &#x27;any&#x27; is specified it will be pick the first trigger. */
    public var injectTrigger: String?

    public init(name: String, model: Decimal? = nil, clip: Decimal? = nil, injectTrigger: String? = nil) {
        self.name = name
        self.model = model
        self.clip = clip
        self.injectTrigger = injectTrigger
    }

    public enum CodingKeys: String, CodingKey {
        case name
        case model
        case clip
        case injectTrigger = "inject_trigger"
    }
}
