//
// NoValidRequestFound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct NoValidRequestFound: Codable {
    /** How many waiting requests were skipped because they demanded a specific worker */
    public var workerId: Int?
    /** How many waiting requests were skipped because they required higher performance */
    public var performance: Int?
    /** How many waiting requests were skipped because they demanded a nsfw generation which this worker does not provide. */
    public var nsfw: Int?
    /** How many waiting requests were skipped because they demanded a generation with a word that this worker does not accept. */
    public var blacklist: Int?
    /** How many waiting requests were skipped because they demanded a trusted worker which this worker is not. */
    public var untrusted: Int?
    /** How many waiting requests were skipped because they demanded a different model than what this worker provides. */
    public var models: Int?
    /** How many waiting requests were skipped because they require a higher version of the bridge than this worker is running (upgrade if you see this in your skipped list). */
    public var bridgeVersion: Int?
    /** How many waiting requests were skipped because the user didn&#x27;t have enough kudos when this worker requires upfront kudos */
    public var kudos: Int?

    public init(workerId: Int? = nil, performance: Int? = nil, nsfw: Int? = nil, blacklist: Int? = nil, untrusted: Int? = nil, models: Int? = nil, bridgeVersion: Int? = nil, kudos: Int? = nil) {
        self.workerId = workerId
        self.performance = performance
        self.nsfw = nsfw
        self.blacklist = blacklist
        self.untrusted = untrusted
        self.models = models
        self.bridgeVersion = bridgeVersion
        self.kudos = kudos
    }

    public enum CodingKeys: String, CodingKey {
        case workerId = "worker_id"
        case performance
        case nsfw
        case blacklist
        case untrusted
        case models
        case bridgeVersion = "bridge_version"
        case kudos
    }
}
