//
// PopInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct PopInput: Codable {
    /** The Name of the Worker */
    public var name: String?
    public var priorityUsernames: [String]?
    /** Whether this worker can generate NSFW requests or not. */
    public var nsfw: Bool?
    public var models: [String]?
    /** The version of the bridge used by this worker */
    public var bridgeVersion: Int?
    /** The worker name, version and website */
    public var bridgeAgent: String?
    /** How many threads this worker is running. This is used to accurately the current power available in the horde */
    public var threads: Int?
    /** If True, this worker will only pick up requests where the owner has the required kudos to consume already available. */
    public var requireUpfrontKudos: Bool?

    public init(name: String? = nil, priorityUsernames: [String]? = nil, nsfw: Bool? = nil, models: [String]? = nil, bridgeVersion: Int? = nil, bridgeAgent: String? = nil, threads: Int? = nil, requireUpfrontKudos: Bool? = nil) {
        self.name = name
        self.priorityUsernames = priorityUsernames
        self.nsfw = nsfw
        self.models = models
        self.bridgeVersion = bridgeVersion
        self.bridgeAgent = bridgeAgent
        self.threads = threads
        self.requireUpfrontKudos = requireUpfrontKudos
    }

    public enum CodingKeys: String, CodingKey {
        case name
        case priorityUsernames = "priority_usernames"
        case nsfw
        case models
        case bridgeVersion = "bridge_version"
        case bridgeAgent = "bridge_agent"
        case threads
        case requireUpfrontKudos = "require_upfront_kudos"
    }
}
