//
// SimpleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SimpleResponse: Codable {
    /** The result of this operation */
    public var message: String

    public init(message: String) {
        self.message = message
    }
}
