//
// SubmitInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubmitInput: Codable {

    public enum State: String, Codable { 
        case ok = "ok"
        case censored = "censored"
        case faulted = "faulted"
        case csam = "csam"
    }
    /** The UUID of this generation */
    public var _id: String
    /** R2 result was uploaded to R2, else the string of the result. */
    public var generation: String?
    /** The state of this generation. */
    public var state: State?

    public init(_id: String, generation: String? = nil, state: State? = nil) {
        self._id = _id
        self.generation = generation
        self.state = state
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case generation
        case state
    }

}
