//
// TeamDetailsLite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TeamDetailsLite: Codable {
    /** The Name given to this team. */
    public var name: String?
    /** The UUID of this team. */
    public var _id: String?

    public init(name: String? = nil, _id: String? = nil) {
        self.name = name
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey {
        case name
        case _id = "id"
    }
}
