//
// UsageDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UsageDetails: Codable {
    /** How many megapixelsteps this user has requested */
    public var megapixelsteps: Decimal?
    /** How many images this user has requested */
    public var requests: Int?

    public init(megapixelsteps: Decimal? = nil, requests: Int? = nil) {
        self.megapixelsteps = megapixelsteps
        self.requests = requests
    }
}
