//
// UserAmountRecords.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UserAmountRecords: Codable {
    /** How many images this user has generated or requested */
    public var image: Int?
    /** How many texts this user has generated or requested */
    public var text: Int?
    /** How many texts this user has generated or requested */
    public var interrogation: Int?

    public init(image: Int? = nil, text: Int? = nil, interrogation: Int? = nil) {
        self.image = image
        self.text = text
        self.interrogation = interrogation
    }
}
