//
// V2FiltersBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct V2FiltersBody: Codable {
    public var prompt: String?
    public var filterType: Int?

    public init(prompt: String? = nil, filterType: Int? = nil) {
        self.prompt = prompt
        self.filterType = filterType
    }

    public enum CodingKeys: String, CodingKey {
        case prompt
        case filterType = "filter_type"
    }
}
