//
// UserThingRecords.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UserThingRecords: Codable {
    /** How many megapixelsteps this user has generated or requested */
    public var megapixelsteps: Decimal?
    /** How many token this user has generated or requested */
    public var tokens: Int?

    public init(megapixelsteps: Decimal? = nil, tokens: Int? = nil) {
        self.megapixelsteps = megapixelsteps
        self.tokens = tokens
    }
}
