//
// ModifyWorkerInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ModifyWorkerInput: Codable {
    /** Set to true to put this worker into maintenance. */
    public var maintenance: Bool?
    /** if maintenance is True, you can optionally provide a message to be used instead of the default maintenance message, so that the owner is informed. */
    public var maintenanceMsg: String?
    /** (Mods only) Set to true to pause this worker. */
    public var paused: Bool?
    /** You can optionally provide a server note which will be seen in the server details. No profanity allowed! */
    public var info: String?
    /** When this is set, it will change the worker&#x27;s name. No profanity allowed! */
    public var name: String?
    /** The team towards which this worker contributes kudos.  It an empty string (&#x27;&#x27;) is passed, it will leave the worker without a team. No profanity allowed! */
    public var team: String?

    public init(maintenance: Bool? = nil, maintenanceMsg: String? = nil, paused: Bool? = nil, info: String? = nil, name: String? = nil, team: String? = nil) {
        self.maintenance = maintenance
        self.maintenanceMsg = maintenanceMsg
        self.paused = paused
        self.info = info
        self.name = name
        self.team = team
    }

    public enum CodingKeys: String, CodingKey {
        case maintenance
        case maintenanceMsg = "maintenance_msg"
        case paused
        case info
        case name
        case team
    }
}
