//
// ModifyWorker.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ModifyWorker: Codable {
    /** The new state of the &#x27;maintenance&#x27; var for this worker. When True, this worker will not pick up any new requests. */
    public var maintenance: Bool?
    /** The new state of the &#x27;paused&#x27; var for this worker. When True, this worker will not be given any new requests. */
    public var paused: Bool?
    /** The new state of the &#x27;info&#x27; var for this worker. */
    public var info: String?
    /** The new name for this this worker. */
    public var name: String?
    /** The new team of this worker. */
    public var team: String?

    public init(maintenance: Bool? = nil, paused: Bool? = nil, info: String? = nil, name: String? = nil, team: String? = nil) {
        self.maintenance = maintenance
        self.paused = paused
        self.info = info
        self.name = name
        self.team = team
    }
}
