//
// RequestInterrogationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct RequestInterrogationResponse: Codable {
    /** The UUID of the request. Use this to retrieve the request status in the future */
    public var _id: String?
    /** Any extra information from the horde about this request */
    public var message: String?

    public init(_id: String? = nil, message: String? = nil) {
        self._id = _id
        self.message = message
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case message
    }
}
