//
// TeamDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TeamDetails: Codable {
    /** The Name given to this team. */
    public var name: String?
    /** The UUID of this team. */
    public var _id: String?
    /** Extra information or comments about this team provided by its owner. */
    public var info: String?
    /** How many images this team&#x27;s workers have generated. */
    public var requestsFulfilled: Int?
    /** How many Kudos the workers in this team have been rewarded while part of this team. */
    public var kudos: Decimal?
    /** The total amount of time workers have stayed online while on this team */
    public var uptime: Int?
    /** The alias of the user which created this team. */
    public var creator: String?
    /** How many workers have been dedicated to this team */
    public var workerCount: Int?
    public var workers: [WorkerDetailsLite]?
    public var models: [ActiveModelLite]?

    public init(name: String? = nil, _id: String? = nil, info: String? = nil, requestsFulfilled: Int? = nil, kudos: Decimal? = nil, uptime: Int? = nil, creator: String? = nil, workerCount: Int? = nil, workers: [WorkerDetailsLite]? = nil, models: [ActiveModelLite]? = nil) {
        self.name = name
        self._id = _id
        self.info = info
        self.requestsFulfilled = requestsFulfilled
        self.kudos = kudos
        self.uptime = uptime
        self.creator = creator
        self.workerCount = workerCount
        self.workers = workers
        self.models = models
    }

    public enum CodingKeys: String, CodingKey {
        case name
        case _id = "id"
        case info
        case requestsFulfilled = "requests_fulfilled"
        case kudos
        case uptime
        case creator
        case workerCount = "worker_count"
        case workers
        case models
    }
}
