//
// DatasetsGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DatasetsGetResponse: Codable {

    /** The unique identifier for this dataset */
    public var _id: String?
    /** The name of this dataset */
    public var name: String?
    /** The description of this dataset */
    public var _description: String?
    /** The number of images in this dataset */
    public var imageCount: Int?

    public init(_id: String? = nil, name: String? = nil, _description: String? = nil, imageCount: Int? = nil) {
        self._id = _id
        self.name = name
        self._description = _description
        self.imageCount = imageCount
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case imageCount = "image_count"
    }

}
