//
// RatePostResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatePostResponse: Codable {

    /** Any extra information about the submitted rating */
    public var message: String?
    /** The amount of kudos awarded for this rating */
    public var reward: Int?

    public init(message: String? = nil, reward: Int? = nil) {
        self.message = message
        self.reward = reward
    }


}
