//
// RatingSetBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingSetBody: Codable {

    public var _set: String?
    public var ratings: String?
    public var best: String?
    public var allSetIds: String?
    public var user: String?
    public var clientAgent: String?

    public init(_set: String? = nil, ratings: String? = nil, best: String? = nil, allSetIds: String? = nil, user: String? = nil, clientAgent: String? = nil) {
        self._set = _set
        self.ratings = ratings
        self.best = best
        self.allSetIds = allSetIds
        self.user = user
        self.clientAgent = clientAgent
    }

    public enum CodingKeys: String, CodingKey { 
        case _set = "set"
        case ratings
        case best
        case allSetIds = "all_set_ids"
        case user
        case clientAgent = "client_agent"
    }

}
