//
// InterrogationPopFormPayload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InterrogationPopFormPayload: Codable {

    public enum Form: String, Codable { 
        case caption = "caption"
        case interrogation = "interrogation"
        case nsfw = "nsfw"
        case gfpgan = "GFPGAN"
        case realesrganX4plus = "RealESRGAN_x4plus"
        case realesrganX2plus = "RealESRGAN_x2plus"
        case realesrganX4plusAnime6b = "RealESRGAN_x4plus_anime_6B"
        case nmkdSiax = "NMKD_Siax"
        case _4xAnimeSharp = "4x_AnimeSharp"
        case codeFormers = "CodeFormers"
        case stripBackground = "strip_background"
    }
    /** The UUID of the interrogation form. Use this to post the results in the future */
    public var _id: String?
    /** The name of this interrogation form */
    public var form: Form?
    public var payload: String?
    /** The URL From which the source image can be downloaded. */
    public var sourceImage: String?
    /** The URL in which the post-processed image can be uploaded. */
    public var r2Upload: String?

    public init(_id: String? = nil, form: Form? = nil, payload: String? = nil, sourceImage: String? = nil, r2Upload: String? = nil) {
        self._id = _id
        self.form = form
        self.payload = payload
        self.sourceImage = sourceImage
        self.r2Upload = r2Upload
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case form
        case payload
        case sourceImage = "source_image"
        case r2Upload = "r2_upload"
    }

}
