//
// SharedKeyDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SharedKeyDetails: Codable {

    /** The SharedKey ID */
    public var _id: String?
    /** The owning user&#x27;s unique Username. It is a combination of their chosen alias plus their ID. */
    public var username: String?
    /** The Kudos limit assigned to this key */
    public var kudos: Int?
    /** The date at which this API key will expire. */
    public var expiry: Date?
    /** How mych kudos has been utilized via this shared key until now. */
    public var utilized: Int?

    public init(_id: String? = nil, username: String? = nil, kudos: Int? = nil, expiry: Date? = nil, utilized: Int? = nil) {
        self._id = _id
        self.username = username
        self.kudos = kudos
        self.expiry = expiry
        self.utilized = utilized
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case kudos
        case expiry
        case utilized
    }

}
