//
// ContributionsDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContributionsDetails: Codable {

    /** How many megapixelsteps this user has generated */
    public var megapixelsteps: Decimal?
    /** How many images this user has generated */
    public var fulfillments: Int?

    public init(megapixelsteps: Decimal? = nil, fulfillments: Int? = nil) {
        self.megapixelsteps = megapixelsteps
        self.fulfillments = fulfillments
    }


}
