//
// FilterPromptSuspicion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FilterPromptSuspicion: Codable {

    /** Rates how suspicious the provided prompt is. A suspicion over 2 means it would be blocked. */
    public var suspicion: String
    public var matches: [String]?

    public init(suspicion: String, matches: [String]? = nil) {
        self.suspicion = suspicion
        self.matches = matches
    }


}
