//
// GenerationPayload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GenerationPayload: Codable {

    public var payload: ModelPayloadKobold?
    /** The UUID for this text generation */
    public var _id: String?
    public var skipped: NoValidRequestFoundKobold?
    /** The soft prompt requested for this generation */
    public var softprompt: String?
    /** Which of the available models to use for this request */
    public var model: String?

    public init(payload: ModelPayloadKobold? = nil, _id: String? = nil, skipped: NoValidRequestFoundKobold? = nil, softprompt: String? = nil, model: String? = nil) {
        self.payload = payload
        self._id = _id
        self.skipped = skipped
        self.softprompt = softprompt
        self.model = model
    }

    public enum CodingKeys: String, CodingKey { 
        case payload
        case _id = "id"
        case skipped
        case softprompt
        case model
    }

}
