//
// ImgModelStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImgModelStats: Codable {

    public var day: Int?
    public var month: Int?
    public var total: Int?

    public init(day: Int? = nil, month: Int? = nil, total: Int? = nil) {
        self.day = day
        self.month = month
        self.total = total
    }


}
