//
// InterrogateSubmitBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InterrogateSubmitBody: Codable {

    public var _id: String?
    public var result: String?
    public var state: String?

    public init(_id: String? = nil, result: String? = nil, state: String? = nil) {
        self._id = _id
        self.result = result
        self.state = state
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case result
        case state
    }

}
