//
// ModelInterrogationFormStable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelInterrogationFormStable: Codable {

    public enum Name: String, Codable { 
        case caption = "caption"
        case interrogation = "interrogation"
        case nsfw = "nsfw"
        case gfpgan = "GFPGAN"
        case realesrganX4plus = "RealESRGAN_x4plus"
        case realesrganX2plus = "RealESRGAN_x2plus"
        case realesrganX4plusAnime6b = "RealESRGAN_x4plus_anime_6B"
        case nmkdSiax = "NMKD_Siax"
        case _4xAnimeSharp = "4x_AnimeSharp"
        case codeFormers = "CodeFormers"
        case stripBackground = "strip_background"
    }
    /** The type of interrogation this is */
    public var name: Name
    public var payload: String?

    public init(name: Name, payload: String? = nil) {
        self.name = name
        self.payload = payload
    }


}
