//
// Newspiece.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Newspiece: Codable {

    /** The date this newspiece was published */
    public var datePublished: String?
    /** The actual piece of news */
    public var newspiece: String?
    /** How critical this piece of news is. */
    public var importance: String?

    public init(datePublished: String? = nil, newspiece: String? = nil, importance: String? = nil) {
        self.datePublished = datePublished
        self.newspiece = newspiece
        self.importance = importance
    }

    public enum CodingKeys: String, CodingKey { 
        case datePublished = "date_published"
        case newspiece
        case importance
    }

}
