//
// SinglePeriodTxtModelStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SinglePeriodTxtModelStats: Codable {

    public var : [String:Int]?

    public init(: [String:Int]? = nil) {
        self. = 
    }

    public enum CodingKeys: String, CodingKey { 
        case  = "*"
    }

}
