//
// ModifyUserIdBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ModifyUserIdBody: Codable {
    public var validated: Bool?
    public var flagged: Bool?

    public init(validated: Bool? = nil, flagged: Bool? = nil) {
        self.validated = validated
        self.flagged = flagged
    }
}
